export default {
   GOOGLE_CLIENT_ID: process.env.GOOGLE_CLIENT_ID || '270719396529-au8f8psrrcv4cthstrr9hvrampc0i9tm.apps.googleusercontent.com',
   GOOGLE_CLIENT_SECRET: process.env.GOOGLE_CLIENT_SECRET || 'qJafSqDIOL1dTUu4spWr-vs_',
   GOOGLE_REDIRECT_URL: process.env.GOOGLE_REDIRECT_URL || `https://localhost/api/auth/google/signIn`,
   FACEBOOK_CLIENT_ID: process.env.FACEBOOK_CLIENT_ID || '153316223236099',
   FACEBOOK_CLIENT_SECRET: process.env.FACEBOOK_CLIENT_SECRET || '409a464db2cefea10ae3bd456660c27b',
   FACEBOOK_REDIRECT_URL: process.env.FACEBOOK_REDIRECT_URL || `https://localhost/api/auth/facebook/signIn`,
   GITHUB_CLIENT_ID: process.env.GITHUB_CLIENT_ID || 'd190a1ee223e5d363517',
   GITHUB_CLIENT_SECRET: process.env.GITHUB_CLIENT_SECRET || '5d44fa0dc1b262ec3a2fa5445026564b3f15e4db',
   GITHUB_REDIRECT_URL: process.env.GITHUB_REDIRECT_URL || `https://localhost/api/auth/github/signIn`,
   AWS_ACCESS_KEY: process.env.AWS_ACCESS_KEY || 'AKIATWJLAOISQZNZVZGE',
   AWS_SECRET_KEY: process.env.AWS_SECRET_KEY || '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',
   SG_API_KEY: process.env.SG_API_KEY || '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',
   SG_SENDER_EMAIL: process.env.SG_SENDER_EMAIL || 'fatihsevban.bilkent@gmail.com',
   MONGO_HOST: process.env.MONGO_HOST,
   SERVER_PORT: process.env.SERVER_PORT,
   JWT_SECRET: process.env.JWT_SECRET,
   JWT_EXPIRES_IN: process.env.JWT_EXPIRES_IN,
   AUTH_TYPE_PASSWORD: 'Password',
   AUTH_TYPE_GITHUB: 'GitHub',
   AUTH_TYPE_GOOGLE: 'Google',
   AUTH_TYPE_FACEBOOK: 'Facebook',
}